services:
  postgres:
    image: postgres:18.4
    environment:
      POSTGRES_DB: job_tracker
      POSTGRES_USER: job_tracker
      POSTGRES_PASSWORD: job_tracker_dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: