spring.application.name=Job Application Tracker

spring.datasource.url=jdbc:postgresql://localhost:5432/job_tracker
spring.datasource.username=job_tracker
spring.datasource.password=job_tracker_dev_password
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=PT1H

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false