CREATE TABLE applications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company VARCHAR(255) NOT NULL,
    position VARCHAR(255) NOT NULL,
    job_url VARCHAR(2048),
    job_description TEXT,
    current_status VARCHAR(30) NOT NULL DEFAULT 'APPLIED',
    applied_date DATE NOT NULL,
    follow_up_at TIMESTAMP WITH TIME ZONE,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_applications_status
        CHECK (current_status IN ('APPLIED', 'INTERVIEW', 'OFFER', 'REJECTED'))
);