CREATE TABLE user_skills (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             user_id BIGINT NOT NULL,
                             name VARCHAR(100) NOT NULL,
                             normalized_name VARCHAR(100) NOT NULL,
                             created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

                             CONSTRAINT fk_user_skills_user
                                 FOREIGN KEY (user_id)
                                     REFERENCES users(id)
                                     ON DELETE CASCADE,

                             CONSTRAINT uq_user_skills_user_normalized_name
                                 UNIQUE (user_id, normalized_name),

                             CONSTRAINT chk_user_skills_name_not_blank
                                 CHECK (BTRIM(name) <> '')
);