CREATE TABLE application_events (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    application_id BIGINT NOT NULL,
                                    type VARCHAR(30) NOT NULL,
                                    scheduled_at TIMESTAMP WITH TIME ZONE NOT NULL,
                                    completed_at TIMESTAMP WITH TIME ZONE,
                                    notes TEXT,
                                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                    CONSTRAINT fk_application_events_application
                                        FOREIGN KEY (application_id)
                                            REFERENCES applications(id)
                                            ON DELETE CASCADE,

                                    CONSTRAINT chk_application_events_type
                                        CHECK (type IN ('INTERVIEW', 'FOLLOW_UP', 'DEADLINE', 'OTHER'))
);

CREATE INDEX idx_application_events_application_id
    ON application_events(application_id);

CREATE INDEX idx_application_events_scheduled_at
    ON application_events(scheduled_at);